name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: List test files
        run: find src -name "test_*.py" -type f

      - name: Show directory structure
        run: find src -type f | sort

      - name: Create __init__.py files for proper imports
        run: |
          find src -type d -exec touch {}/__init__.py \;
          find src -name "__init__.py" | sort

      - name: Run individual tests
        run: |
          for test_file in $(find src -name "test_*.py" -type f); do
            echo "Running $test_file"
            python3 -m unittest $test_file
          done
